{
 "title": "Serving Operacional - Churn API",
 "tags": [
  "prometheus",
  "grafana",
  "serving"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latência P95 /predict",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(churn_serving_predict_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Volume de Requisições /predict",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(churn_serving_predict_requests_total[1m])) * 60",
     "legendFormat": "req/min"
    }
   ]
  },
  {
   "title": "Taxa de Erro 5xx /predict",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(rate(churn_serving_predict_requests_total{status_code=~\"5..\"}[5m])) or vector(0)) / sum(rate(churn_serving_predict_requests_total[5m]))) or vector(0)",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Requisições em Andamento",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "churn_serving_predict_requests_in_progress",
     "legendFormat": "in_progress"
    }
   ]
  },
  {
   "title": "Tempo Feast P95",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(churn_serving_predict_feast_lookup_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Tempo Modelo P95",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(churn_serving_predict_model_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "P95"
    }
   ]
  }
 ]
}